<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla atleta_tipo.
 *
 * Los siguientes son los campos de la tabla 'atleta_tipo':
 * @property integer $id_tipo
 * @property string $tipo_atleta

 * Los siguientes son las relaciones de este modelo :

 * @property Persona_atleta[] $array_persona_atleta
 **/



class Atleta_tipo extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'atleta_tipo';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_tipo';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_persona_atleta'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Atleta_tipo';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_tipo',
      'tipo_atleta'
    ];


	 /**
     * 
     * Get array_persona_atleta
     */
	  public function array_persona_atleta()
		{
			return $this->hasMany(Persona_atleta::class,'id_tipo','id_tipo');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'tipo_atleta' =>'nullable|max:255'
            ],
            'update'=>[
                'id_tipo' =>'required|unique:'.$this->connection.'.atleta_tipo,id_tipo,'.$this->id_tipo.',id_tipo',
                'tipo_atleta' =>'nullable|max:255'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

