<?php
/**
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla cancha.
 *
 * Los siguientes son los campos de la tabla 'cancha':
 * @property integer $id_cancha
 * @property string $nombre_cancha

 * Los siguientes son las relaciones de este modelo :

 * @property Juego[] $array_juego
 **/



class Cancha extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'cancha';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_cancha';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_juego'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Cancha';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_cancha',
      'nombre_cancha'
    ];


	 /**
     * 
     * Get array_juego
     */
	  public function array_juego()
		{
			return $this->hasMany(Juego::class,'id_cancha','id_cancha');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'nombre_cancha' =>'nullable|max:255'
            ],
            'update'=>[
                'id_cancha' =>'required|unique:'.$this->connection.'.cancha,id_cancha,'.$this->id_cancha.',id_cancha',
                'nombre_cancha' =>'nullable|max:255'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

