<?php
/**Generate by ASGENS
*@author Yoan  
*@date Wed Dec 31 12:30:00 GMT-04:00 2025  
*@time Wed Dec 31 12:30:00 GMT-04:00 2025  
*/
namespace Modules\general\Models;

use App\Models\BaseModel;

/**
 * Este es la clase modelo para la tabla compromiso_participacion.
 *
 * Los siguientes son los campos de la tabla 'compromiso_participacion':
 * @property integer $id_compromiso
 * @property integer $id_delegacion_evento
 * @property integer $id_deporte
 *
 * Los siguientes son las relaciones de este modelo :
 *
 * @property Delegacion_evento $delegacion_evento
 * @property Deporte $deporte
 **/

class Compromiso_participacion extends BaseModel
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'compromiso_participacion';

    /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primary key associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_compromiso';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['delegacion_evento','deporte'];

    /**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Compromiso_participacion';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id_compromiso',
        'id_delegacion_evento',
        'id_deporte'
    ];

    /**
     * Get the Delegacion_evento
     */
    public function delegacion_evento()
    {
        return $this->belongsTo(Delegacion_evento::class,'id_delegacion_evento','id_delegacion_evento');
    }

    /**
     * Get the Deporte
     */
    public function deporte()
    {
        return $this->belongsTo(Deporte::class,'id_deporte','id_deporte');
    }

    protected function rules($scenario='create')
    {
        $rules = [
            'create' => [
                'id_delegacion_evento' => 'nullable|exists:'.$this->connection.'.delegacion_evento,id_delegacion_evento',
                'id_deporte' => 'nullable|exists:'.$this->connection.'.deporte,id_deporte'
            ],
            'update' => [
                'id_compromiso' => 'required|unique:'.$this->connection.'.compromiso_participacion,id_compromiso,'.$this->id_compromiso.',id_compromiso',
                'id_delegacion_evento' => 'nullable|exists:'.$this->connection.'.delegacion_evento,id_delegacion_evento',
                'id_deporte' => 'nullable|exists:'.$this->connection.'.deporte,id_deporte'
            ]
        ];
        if (!isset($rules[$scenario])) {
            throw new \Exception('Scenario '.$scenario.' not exist');
        }
        return $rules[$scenario];
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
