<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;

use Illuminate\Support\Carbon;

/**
 * Este es la clase modelo para la tabla congresillo_deporte.
 *
 * Los siguientes son los campos de la tabla 'congresillo_deporte':
 * @property integer $id_congresillo
 * @property Carbon $fecha_congresillo
 * @property integer $id_competencia

 * Los siguientes son las relaciones de este modelo :

 * @property Competencia $competencia
 * @property Congresillo_asistencia[] $array_congresillo_asistencia
 **/



class Congresillo_deporte extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'congresillo_deporte';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_congresillo';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['competencia','array_congresillo_asistencia'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Congresillo_deporte';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_congresillo',
      'fecha_congresillo',
      'id_competencia'
    ];

	 /**
     * Get the Competencia
     */
	  public function competencia()
		{
			return $this->belongsTo(Competencia::class,'id_competencia','id_competencia');
		}


	 /**
     * 
     * Get array_congresillo_asistencia
     */
	  public function array_congresillo_asistencia()
		{
			return $this->hasMany(Congresillo_asistencia::class,'id_congresillo','id_congresillo');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'fecha_congresillo' =>'nullable|date',
                'id_competencia' =>'nullable|exists:'.$this->connection.'.competencia,id_competencia'
            ],
            'update'=>[
                'id_congresillo' =>'required|unique:'.$this->connection.'.congresillo_deporte,id_congresillo,'.$this->id_congresillo.',id_congresillo',
                'fecha_congresillo' =>'nullable|date',
                'id_competencia' =>'nullable|exists:'.$this->connection.'.competencia,id_competencia'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

