<?php
/**
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla congresillo_asistencia.
 *
 * Los siguientes son los campos de la tabla 'congresillo_asistencia':
 * @property integer $id_asistencia_congresillo
 * @property string $representante
 * @property integer $id_delegacion
 * @property integer $id_congresillo

 * Los siguientes son las relaciones de este modelo :

 * @property Delegacion $delegacion
 * @property Congresillo_deporte $congresillo
 **/



class Congresillo_asistencia extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'congresillo_asistencia';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_asistencia_congresillo';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['delegacion','congresillo'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Congresillo_asistencia';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_asistencia_congresillo',
      'representante',
      'id_delegacion',
      'id_congresillo'
    ];

	 /**
     * Get the Delegacion
     */
	  public function delegacion()
		{
			return $this->belongsTo(Delegacion::class,'id_delegacion','id_delegacion');
		}

	 /**
     * Get the Congresillo_deporte
     */
	  public function congresillo()
		{
			return $this->belongsTo(Congresillo_deporte::class,'id_congresillo','id_congresillo');
		}



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'representante' =>'nullable|max:255',
                'id_delegacion' =>'nullable|exists:'.$this->connection.'.delegacion,id_delegacion',
                'id_congresillo' =>'nullable|exists:'.$this->connection.'.congresillo_deporte,id_congresillo'
            ],
            'update'=>[
                'id_asistencia_congresillo' =>'required|unique:'.$this->connection.'.congresillo_asistencia,id_asistencia_congresillo,'.$this->id_asistencia_congresillo.',id_asistencia_congresillo',
                'representante' =>'nullable|max:255',
                'id_delegacion' =>'nullable|exists:'.$this->connection.'.delegacion,id_delegacion',
                'id_congresillo' =>'nullable|exists:'.$this->connection.'.congresillo_deporte,id_congresillo'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

