<?php
/**
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla delegacion_tipo.
 *
 * Los siguientes son los campos de la tabla 'delegacion_tipo':
 * @property integer $id_tipo_delegacion
 * @property string $tipo_delegacion

 * Los siguientes son las relaciones de este modelo :

 * @property Delegacion[] $array_delegacion
 **/



class Delegacion_tipo extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'delegacion_tipo';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_tipo_delegacion';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_delegacion'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Delegacion_tipo';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_tipo_delegacion',
      'tipo_delegacion'
    ];


	 /**
     * 
     * Get array_delegacion
     */
	  public function array_delegacion()
		{
			return $this->hasMany(Delegacion::class,'id_tipo_delegacion','id_tipo_delegacion');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'tipo_delegacion' =>'nullable|max:255'
            ],
            'update'=>[
                'id_tipo_delegacion' =>'required|unique:'.$this->connection.'.delegacion_tipo,id_tipo_delegacion,'.$this->id_tipo_delegacion.',id_tipo_delegacion',
                'tipo_delegacion' =>'nullable|max:255'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

