<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla delegacion_regla.
 *
 * Los siguientes son los campos de la tabla 'delegacion_regla':
 * @property integer $id_regla_delegacion
 * @property string $nombre_regla
 * @property string $regla

 * Los siguientes son las relaciones de este modelo :

 * @property Delegacion[] $array_delegacion
 **/



class Delegacion_regla extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'delegacion_regla';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_regla_delegacion';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_delegacion'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Delegacion_regla';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_regla_delegacion',
      'nombre_regla',
      'regla'
    ];


	 /**
     * 
     * Get array_delegacion
     */
	  public function array_delegacion()
		{
			return $this->hasMany(Delegacion::class,'id_regla_delegacion','id_regla_delegacion');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'nombre_regla' =>'nullable|max:255',
                'regla' =>'nullable'
            ],
            'update'=>[
                'id_regla_delegacion' =>'required|unique:'.$this->connection.'.delegacion_regla,id_regla_delegacion,'.$this->id_regla_delegacion.',id_regla_delegacion',
                'nombre_regla' =>'nullable|max:255',
                'regla' =>'nullable'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

