<?php
/**
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla delegacion_evento.
 *
 * Los siguientes son los campos de la tabla 'delegacion_evento':
 * @property integer $id_delegacion_evento
 * @property integer $id_evento
 * @property integer $id_delegacion

 * Los siguientes son las relaciones de este modelo :

 * @property Evento_deportivo $evento
 * @property Delegacion $delegacion
 **/



class Delegacion_evento extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'delegacion_evento';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_delegacion_evento';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['evento','delegacion'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Delegacion_evento';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_delegacion_evento',
      'id_evento',
      'id_delegacion'
    ];

	 /**
     * Get the Evento_deportivo
     */
	  public function evento()
		{
			return $this->belongsTo(Evento_deportivo::class,'id_evento','id_evento');
		}

	 /**
     * Get the Delegacion
     */
	  public function delegacion()
		{
			return $this->belongsTo(Delegacion::class,'id_delegacion','id_delegacion');
		}
    
  
    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'id_evento' =>'nullable|exists:'.$this->connection.'.evento_deportivo,id_evento',
                'id_delegacion' =>'nullable|exists:'.$this->connection.'.delegacion,id_delegacion'
            ],
            'update'=>[
                'id_delegacion_evento' =>'required|unique:'.$this->connection.'.delegacion_evento,id_delegacion_evento,'.$this->id_delegacion_evento.',id_delegacion_evento',
                'id_evento' =>'nullable|exists:'.$this->connection.'.evento_deportivo,id_evento',
                'id_delegacion' =>'nullable|exists:'.$this->connection.'.delegacion,id_delegacion'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

