<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla deporte_categoria_puntuacion.
 *
 * Los siguientes son los campos de la tabla 'deporte_categoria_puntuacion':
 * @property integer $id_categoria
 * @property string $nombre_categoria
 * @property string $puntos

 * Los siguientes son las relaciones de este modelo :

 * @property Deporte[] $array_deporte
 **/



class Deporte_categoria_puntuacion extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'deporte_categoria_puntuacion';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_categoria';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_deporte'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Deporte_categoria_puntuacion';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_categoria',
      'nombre_categoria',
      'puntos'
    ];


	 /**
     * 
     * Get array_deporte
     */
	  public function array_deporte()
		{
			return $this->hasMany(Deporte::class,'id_categoria','id_categoria');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'nombre_categoria' =>'nullable|max:255',
                'puntos' =>'nullable|max:255'
            ],
            'update'=>[
                'id_categoria' =>'required|unique:'.$this->connection.'.deporte_categoria_puntuacion,id_categoria,'.$this->id_categoria.',id_categoria',
                'nombre_categoria' =>'nullable|max:255',
                'puntos' =>'nullable|max:255'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

