<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla deporte_regla.
 *
 * Los siguientes son los campos de la tabla 'deporte_regla':
 * @property integer $id_regla_deporte
 * @property string $nombre_regla
 * @property string $campos
 * @property string $cal_campos

 * Los siguientes son las relaciones de este modelo :

 * @property Deporte[] $array_deporte
 **/



class Deporte_regla extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'deporte_regla';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_regla_deporte';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


/**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_deporte'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Deporte_regla';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_regla_deporte',
      'nombre_regla',
      'campos',
      'cal_campos'
    ];


	 /**
     * 
     * Get array_deporte
     */
	  public function array_deporte()
		{
			return $this->hasMany(Deporte::class,'id_regla','id_regla_deporte');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'id_regla_deporte' =>'required|unique:'.$this->connection.'.deporte_regla',
                'nombre_regla' =>'nullable|max:255',
                'campos' =>'nullable',
                'cal_campos' =>'nullable'
            ],
            'update'=>[
                'id_regla_deporte' =>'required|unique:'.$this->connection.'.deporte_regla,id_regla_deporte,'.$this->id_regla_deporte.',id_regla_deporte',
                'nombre_regla' =>'nullable|max:255',
                'campos' =>'nullable',
                'cal_campos' =>'nullable'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

