<?php
/**
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla equipo_atleta.
 *
 * Los siguientes son los campos de la tabla 'equipo_atleta':
 * @property integer $id_equipo_atleta
 * @property integer $id_equipo
 * @property integer $id_atleta
 * @property integer $id_estado_atleta
 * @property boolean $capitan
 * @property boolean $subcapitan

 * Los siguientes son las relaciones de este modelo :

 * @property Equipo $equipo
 * @property Persona_atleta $atleta
 * @property Atleta_estado $estado_atleta
 **/



class Equipo_atleta extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'equipo_atleta';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_equipo_atleta';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


/**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = true;

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Equipo_atleta';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_equipo_atleta',
      'id_equipo',
      'id_atleta',
      'id_estado_atleta',
      'capitan',
      'subcapitan'
    ];

	 /**
     * Get the Equipo
     */
	  public function equipo()
		{
			return $this->belongsTo(Equipo::class,'id_equipo','id_equipo');
		}

	 /**
     * Get the Persona_atleta
     */
	  public function atleta()
		{
			return $this->belongsTo(Persona_atleta::class,'id_atleta','id_atleta');
		}

	 /**
     * Get the Atleta_estado
     */
	  public function estado_atleta()
		{
			return $this->belongsTo(Atleta_estado::class,'id_estado_atleta','id_estado');
		}



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'id_equipo' =>'required|exists:'.$this->connection.'.equipo,id_equipo',
                'id_atleta' =>'required|exists:'.$this->connection.'.persona_atleta,id_atleta',
                'id_estado_atleta' =>'required|exists:'.$this->connection.'.atleta_estado,id_estado',
                'capitan' =>'nullable|boolean',
                'subcapitan' =>'nullable|boolean'
            ],
            'update'=>[
                'id_equipo' =>'required|exists:'.$this->connection.'.equipo,id_equipo',
                'id_atleta' =>'required|exists:'.$this->connection.'.persona_atleta,id_atleta',
                'id_estado_atleta' =>'required|exists:'.$this->connection.'.atleta_estado,id_estado',
                'capitan' =>'nullable|boolean',
                'subcapitan' =>'nullable|boolean'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

