<?php
/**
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla equipo.
 *
 * Los siguientes son los campos de la tabla 'equipo':
 * @property integer $id_equipo
 * @property string $nombre_equipo
 * @property integer $id_competencia
 * @property integer $id_delegacion
 * @property integer $id_estado

 * Los siguientes son las relaciones de este modelo :

 * @property Competencia $competencia
 * @property Equipo_estado $estado
 * @property Delegacion $delegacion
 * @property Equipo_atleta[] $array_equipo_atleta
 **/



class Equipo extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'equipo';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_equipo';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['competencia','estado','delegacion','array_equipo_atleta'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Equipo';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_equipo',
      'nombre_equipo',
      'id_competencia',
      'id_delegacion',
      'id_estado'
    ];

	 /**
     * Get the Competencia
     */
	  public function competencia()
		{
			return $this->belongsTo(Competencia::class,'id_competencia','id_competencia');
		}

	 /**
     * Get the Equipo_estado
     */
	  public function estado()
		{
			return $this->belongsTo(Equipo_estado::class,'id_estado','id_estado');
		}

	 /**
     * Get the Delegacion
     */
	  public function delegacion()
		{
			return $this->belongsTo(Delegacion::class,'id_delegacion','id_delegacion');
		}


	 /**
     * 
     * Get array_equipo_atleta
     */
	  public function array_equipo_atleta()
		{
			return $this->hasMany(Equipo_atleta::class,'id_equipo','id_equipo');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'nombre_equipo' =>'nullable|max:255',
                'id_competencia' =>'nullable|exists:'.$this->connection.'.competencia,id_competencia',
                'id_delegacion' =>'nullable|exists:'.$this->connection.'.delegacion,id_delegacion',
                'id_estado' =>'nullable|exists:'.$this->connection.'.equipo_estado,id_estado'
            ],
            'update'=>[
                'id_equipo' =>'required|unique:'.$this->connection.'.equipo,id_equipo,'.$this->id_equipo.',id_equipo',
                'nombre_equipo' =>'nullable|max:255',
                'id_competencia' =>'nullable|exists:'.$this->connection.'.competencia,id_competencia',
                'id_delegacion' =>'nullable|exists:'.$this->connection.'.delegacion,id_delegacion',
                'id_estado' =>'nullable|exists:'.$this->connection.'.equipo_estado,id_estado'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

