<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla evento_deportivo_regla.
 *
 * Los siguientes son los campos de la tabla 'evento_deportivo_regla':
 * @property integer $id_regla_evento
 * @property string $nombre_regla
 * @property string $regla

 * Los siguientes son las relaciones de este modelo :

 * @property Evento_deportivo[] $array_evento_deportivo
 **/



class Evento_deportivo_regla extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'evento_deportivo_regla';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_regla_evento';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_evento_deportivo'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Evento_deportivo_regla';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_regla_evento',
      'nombre_regla',
      'regla'
    ];


	 /**
     * 
     * Get array_evento_deportivo
     */
	  public function array_evento_deportivo()
		{
			return $this->hasMany(Evento_deportivo::class,'id_regla_evento','id_regla_evento');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'nombre_regla' =>'nullable|max:255',
                'regla' =>'nullable'
            ],
            'update'=>[
                'id_regla_evento' =>'required|unique:'.$this->connection.'.evento_deportivo_regla,id_regla_evento,'.$this->id_regla_evento.',id_regla_evento',
                'nombre_regla' =>'nullable|max:255',
                'regla' =>'nullable'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

