<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla juego_fase.
 *
 * Los siguientes son los campos de la tabla 'juego_fase':
 * @property integer $id_fase
 * @property string $nombre_fase
 * @property boolean $es_final

 * Los siguientes son las relaciones de este modelo :

 * @property Juego[] $array_juego
 **/



class Juego_fase extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'juego_fase';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_fase';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_juego'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Juego_fase';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_fase',
      'nombre_fase',
      'es_final'
    ];


	 /**
     * 
     * Get array_juego
     */
	  public function array_juego()
		{
			return $this->hasMany(Juego::class,'id_fase','id_fase');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'nombre_fase' =>'nullable|max:255',
                'es_final' =>'nullable|boolean'
            ],
            'update'=>[
                'id_fase' =>'required|unique:'.$this->connection.'.juego_fase,id_fase,'.$this->id_fase.',id_fase',
                'nombre_fase' =>'nullable|max:255',
                'es_final' =>'nullable|boolean'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

