<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;

use Illuminate\Support\Carbon;

/**
 * Este es la clase modelo para la tabla juego.
 *
 * Los siguientes son los campos de la tabla 'juego':
 * @property integer $id_juego
 * @property Carbon $fecha_inicio
 * @property Carbon $fecha_fin
 * @property string $descripcion_juego
 * @property integer $id_competencia
 * @property integer $id_fase
 * @property integer $id_cancha

 * Los siguientes son las relaciones de este modelo :

 * @property Competencia $competencia
 * @property Juego_fase $fase
 * @property Cancha $cancha
 * @property Juego_delegacion[] $array_juego_delegacion
 **/



class Juego extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'juego';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_juego';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['competencia','fase','cancha','array_juego_delegacion'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Juego';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_juego',
      'fecha_inicio',
      'fecha_fin',
      'descripcion_juego',
      'id_competencia',
      'id_fase',
      'id_cancha'
    ];

	 /**
     * Get the Competencia
     */
	  public function competencia()
		{
			return $this->belongsTo(Competencia::class,'id_competencia','id_competencia');
		}

	 /**
     * Get the Juego_fase
     */
	  public function fase()
		{
			return $this->belongsTo(Juego_fase::class,'id_fase','id_fase');
		}

	 /**
     * Get the Cancha
     */
	  public function cancha()
		{
			return $this->belongsTo(Cancha::class,'id_cancha','id_cancha');
		}


	 /**
     * 
     * Get array_juego_delegacion
     */
	  public function array_juego_delegacion()
		{
			return $this->hasMany(Juego_delegacion::class,'id_juego','id_juego');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'fecha_inicio' =>'nullable|date',
                'fecha_fin' =>'nullable|date',
                'descripcion_juego' =>'nullable|max:255',
                'id_competencia' =>'nullable|exists:'.$this->connection.'.competencia,id_competencia',
                'id_fase' =>'nullable|exists:'.$this->connection.'.juego_fase,id_fase',
                'id_cancha' =>'nullable|exists:'.$this->connection.'.cancha,id_cancha'
            ],
            'update'=>[
                'id_juego' =>'required|unique:'.$this->connection.'.juego,id_juego,'.$this->id_juego.',id_juego',
                'fecha_inicio' =>'nullable|date',
                'fecha_fin' =>'nullable|date',
                'descripcion_juego' =>'nullable|max:255',
                'id_competencia' =>'nullable|exists:'.$this->connection.'.competencia,id_competencia',
                'id_fase' =>'nullable|exists:'.$this->connection.'.juego_fase,id_fase',
                'id_cancha' =>'nullable|exists:'.$this->connection.'.cancha,id_cancha'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

