<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla juego_delegacion.
 *
 * Los siguientes son los campos de la tabla 'juego_delegacion':
 * @property integer $id_juego_delegacion
 * @property integer $id_juego
 * @property integer $id_delegacion
 * @property string $resultados

 * Los siguientes son las relaciones de este modelo :

 * @property Juego $juego
 * @property Delegacion $delegacion
 **/



class Juego_delegacion extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'juego_delegacion';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_juego_delegacion';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['juego','delegacion'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Juego_delegacion';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_juego_delegacion',
      'id_juego',
      'id_delegacion',
      'resultados'
    ];

	 /**
     * Get the Juego
     */
	  public function juego()
		{
			return $this->belongsTo(Juego::class,'id_juego','id_juego');
		}

	 /**
     * Get the Delegacion
     */
	  public function delegacion()
		{
			return $this->belongsTo(Delegacion::class,'id_delegacion','id_delegacion');
		}



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'id_juego' =>'nullable|exists:'.$this->connection.'.juego,id_juego',
                'id_delegacion' =>'nullable|exists:'.$this->connection.'.delegacion,id_delegacion',
                'resultados' =>'nullable'
            ],
            'update'=>[
                'id_juego_delegacion' =>'required|unique:'.$this->connection.'.juego_delegacion,id_juego_delegacion,'.$this->id_juego_delegacion.',id_juego_delegacion',
                'id_juego' =>'nullable|exists:'.$this->connection.'.juego,id_juego',
                'id_delegacion' =>'nullable|exists:'.$this->connection.'.delegacion,id_delegacion',
                'resultados' =>'nullable'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

