<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;

use Modules\security\Models\Usuarios;

/**
 * Este es la clase modelo para la tabla persona.
 *
 * Los siguientes son los campos de la tabla 'persona':
 * @property integer $id_persona
 * @property string $nombre
 * @property string $apellido
 * @property string $carnet
 * @property string $genero
 * @property string $facultad


 * Los siguientes son las relaciones de este modelo :
 * @property Persona_arbitro[] $array_persona_arbitro
 * @property Persona_atleta[] $array_persona_atleta
 * @property Usuarios[] $array_usuarios
 **/



class Persona extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'persona';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_persona';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_persona_arbitro','array_persona_atleta','array_usuarios'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Persona';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_persona',
      'nombre',
      'apellido',
      'carnet',
      'genero',
      'facultad'
    ];


	 /**
     * 
     * Get array_persona_arbitro
     */
	  public function array_persona_arbitro()
		{
			return $this->hasMany(Persona_arbitro::class,'id_persona','id_persona');
		}

	 /**
     * 
     * Get array_persona_atleta
     */
	  public function array_persona_atleta()
		{
			return $this->hasMany(Persona_atleta::class,'id_persona','id_persona');
		}

	 /**
     * 
     * Get array_usuarios
     */
	  public function array_usuarios()
		{
			return $this->hasMany(Usuarios::class,'id_persona','id_persona');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'nombre' =>'nullable|max:255',
                'apellido' =>'nullable|max:255',
                'carnet' =>'nullable|max:255',
                'genero' =>'nullable|max:255',
                'facultad' =>'nullable|max:255'
            ],
            'update'=>[
                'id_persona' =>'required|unique:'.$this->connection.'.persona,id_persona,'.$this->id_persona.',id_persona',
                'nombre' =>'nullable|max:255',
                'apellido' =>'nullable|max:255',
                'carnet' =>'nullable|max:255',
                'genero' =>'nullable|max:255',
                'facultad' =>'nullable|max:255'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

