<?php
/**
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla persona_arbitro.
 *
 * Los siguientes son los campos de la tabla 'persona_arbitro':
 * @property integer $id_supervisor
 * @property integer $id_persona
 * @property integer $id_deporte

 * Los siguientes son las relaciones de este modelo :

 * @property Persona $persona
 * @property Deporte $deporte
 * @property Competencia[] $array_competencia
 **/



class Persona_arbitro extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'persona_arbitro';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_supervisor';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['persona','deporte','array_competencia'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Persona_arbitro';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_supervisor',
      'id_persona',
      'id_deporte'
    ];

	 /**
     * Get the Persona
     */
	  public function persona()
		{
			return $this->belongsTo(Persona::class,'id_persona','id_persona');
		}

	 /**
     * Get the Deporte
     */
	  public function deporte()
		{
			return $this->belongsTo(Deporte::class,'id_deporte','id_deporte');
		}


	 /**
     * 
     * Get array_competencia
     */
	  public function array_competencia()
		{
			return $this->hasMany(Competencia::class,'id_supervisor','id_supervisor');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'id_persona' =>'nullable|exists:'.$this->connection.'.persona,id_persona',
                'id_deporte' =>'nullable|exists:'.$this->connection.'.deporte,id_deporte'
            ],
            'update'=>[
                'id_supervisor' =>'required|unique:'.$this->connection.'.persona_arbitro,id_supervisor,'.$this->id_supervisor.',id_supervisor',
                'id_persona' =>'nullable|exists:'.$this->connection.'.persona,id_persona',
                'id_deporte' =>'nullable|exists:'.$this->connection.'.deporte,id_deporte'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

