<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla persona_atleta.
 *
 * Los siguientes son los campos de la tabla 'persona_atleta':
 * @property integer $id_atleta
 * @property integer $id_persona
 * @property integer $id_tipo
 * @property string $foto
 * @property float $tamaño
 * @property float $peso
 * @property string $facultad

 * Los siguientes son las relaciones de este modelo :

 * @property Persona $persona
 * @property Atleta_tipo $tipo
 * @property Equipo_atleta[] $array_equipo_atleta
 **/



class Persona_atleta extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'persona_atleta';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_atleta';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['persona','tipo','array_equipo_atleta'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Persona_atleta';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_atleta',
      'id_persona',
      'id_tipo',
      'foto',
      'tamaño',
      'peso',
      'facultad'
    ];

	 /**
     * Get the Persona
     */
	  public function persona()
		{
			return $this->belongsTo(Persona::class,'id_persona','id_persona');
		}

	 /**
     * Get the Atleta_tipo
     */
	  public function tipo()
		{
			return $this->belongsTo(Atleta_tipo::class,'id_tipo','id_tipo');
		}


	 /**
     * 
     * Get array_equipo_atleta
     */
	  public function array_equipo_atleta()
		{
			return $this->hasMany(Equipo_atleta::class,'id_atleta','id_atleta');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'id_persona' =>'nullable|exists:'.$this->connection.'.persona,id_persona',
                'id_tipo' =>'nullable|exists:'.$this->connection.'.atleta_tipo,id_tipo',
                'foto' =>'nullable|max:255',
                'tamaño' =>'nullable',
                'peso' =>'nullable',
                'facultad' =>'nullable|max:255'
            ],
            'update'=>[
                'id_atleta' =>'required|unique:'.$this->connection.'.persona_atleta,id_atleta,'.$this->id_atleta.',id_atleta',
                'id_persona' =>'nullable|exists:'.$this->connection.'.persona,id_persona',
                'id_tipo' =>'nullable|exists:'.$this->connection.'.atleta_tipo,id_tipo',
                'foto' =>'nullable|max:255',
                'tamaño' =>'nullable',
                'peso' =>'nullable',
                'facultad' =>'nullable|max:255'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

