<?php
/**
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla reclamacion_estado.
 *
 * Los siguientes son los campos de la tabla 'reclamacion_estado':
 * @property integer $id_estado
 * @property string $nombre_estado

 * Los siguientes son las relaciones de este modelo :

 * @property Reclamacion[] $array_reclamacion
 **/



class Reclamacion_estado extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'reclamacion_estado';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_estado';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_reclamacion'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Reclamacion_estado';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_estado',
      'nombre_estado'
    ];


	 /**
     * 
     * Get array_reclamacion
     */
	  public function array_reclamacion()
		{
			return $this->hasMany(Reclamacion::class,'id_estado','id_estado');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'nombre_estado' =>'nullable|max:255'
            ],
            'update'=>[
                'id_estado' =>'required|unique:'.$this->connection.'.reclamacion_estado,id_estado,'.$this->id_estado.',id_estado',
                'nombre_estado' =>'nullable|max:255'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

