<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;

use Illuminate\Support\Carbon;

/**
 * Este es la clase modelo para la tabla reclamacion.
 *
 * Los siguientes son los campos de la tabla 'reclamacion':
 * @property integer $id_reclamacion
 * @property Carbon $fecha_reclamacion
 * @property string $descripcion_reclamacion
 * @property integer $id_delegacion
 * @property integer $id_sancion
 * @property integer $id_estado

 * Los siguientes son las relaciones de este modelo :

 * @property Delegacion $delegacion
 * @property Sancion $sancion
 * @property Reclamacion_estado $estado
 **/



class Reclamacion extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'reclamacion';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_reclamacion';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


/**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['delegacion','sancion','estado'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Reclamacion';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_reclamacion',
      'fecha_reclamacion',
      'descripcion_reclamacion',
      'id_delegacion',
      'id_sancion',
      'id_estado'
    ];

	 /**
     * Get the Delegacion
     */
	  public function delegacion()
		{
			return $this->belongsTo(Delegacion::class,'id_delegacion','id_delegacion');
		}

	 /**
     * Get the Sancion
     */
	  public function sancion()
		{
			return $this->belongsTo(Sancion::class,'id_sancion','id_sancion');
		}

	 /**
     * Get the Reclamacion_estado
     */
	  public function estado()
		{
			return $this->belongsTo(Reclamacion_estado::class,'id_estado','id_estado');
		}



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'id_reclamacion' =>'required|unique:'.$this->connection.'.reclamacion',
                'fecha_reclamacion' =>'nullable|date',
                'descripcion_reclamacion' =>'nullable|max:255',
                'id_delegacion' =>'nullable|exists:'.$this->connection.'.delegacion,id_delegacion',
                'id_sancion' =>'nullable|exists:'.$this->connection.'.sancion,id_sancion',
                'id_estado' =>'nullable|exists:'.$this->connection.'.reclamacion_estado,id_estado'
            ],
            'update'=>[
                'id_reclamacion' =>'required|unique:'.$this->connection.'.reclamacion,id_reclamacion,'.$this->id_reclamacion.',id_reclamacion',
                'fecha_reclamacion' =>'nullable|date',
                'descripcion_reclamacion' =>'nullable|max:255',
                'id_delegacion' =>'nullable|exists:'.$this->connection.'.delegacion,id_delegacion',
                'id_sancion' =>'nullable|exists:'.$this->connection.'.sancion,id_sancion',
                'id_estado' =>'nullable|exists:'.$this->connection.'.reclamacion_estado,id_estado'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

