<?php
/**Generate by ASGENS
*@author Yoan  
*@date Sat May 10 00:07:04 GMT-04:00 2025  
*@time Sat May 10 00:07:04 GMT-04:00 2025  
*/
namespace Modules\general\Models;


use App\Models\BaseModel;

use Illuminate\Support\Carbon;

/**
 * Este es la clase modelo para la tabla sancion.
 *
 * Los siguientes son los campos de la tabla 'sancion':
 * @property integer $id_sancion
 * @property Carbon $fecha_sancion
 * @property string $razon
 * @property integer $puntos_sancion
 * @property boolean $suspendido
 * @property integer $juegos_suspendidos
 * @property boolean $expulsado
 * @property integer $id_delegacion
 * @property integer $id_competencia

 * Los siguientes son las relaciones de este modelo :

 * @property Delegacion $delegacion
 * @property Competencia $competencia
 * @property Reclamacion[] $array_reclamacion
 **/



class Sancion extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'sancion';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_sancion';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['delegacion','competencia','array_reclamacion'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Sancion';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_sancion',
      'fecha_sancion',
      'razon',
      'puntos_sancion',
      'suspendido',
      'juegos_suspendidos',
      'expulsado',
      'id_delegacion',
      'id_competencia'
    ];

	 /**
     * Get the Delegacion
     */
	  public function delegacion()
		{
			return $this->belongsTo(Delegacion::class,'id_delegacion','id_delegacion');
		}

	 /**
     * Get the Competencia
     */
	  public function competencia()
		{
			return $this->belongsTo(Competencia::class,'id_competencia','id_competencia');
		}


	 /**
     * 
     * Get array_reclamacion
     */
	  public function array_reclamacion()
		{
			return $this->hasMany(Reclamacion::class,'id_sancion','id_sancion');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'fecha_sancion' =>'nullable|date',
                'razon' =>'nullable|max:255',
                'puntos_sancion' =>'nullable',
                'suspendido' =>'nullable|boolean',
                'juegos_suspendidos' =>'nullable',
                'expulsado' =>'nullable|boolean',
                'id_delegacion' =>'nullable|exists:'.$this->connection.'.delegacion,id_delegacion',
                'id_competencia' =>'nullable|exists:'.$this->connection.'.competencia,id_competencia'
            ],
            'update'=>[
                'id_sancion' =>'required|unique:'.$this->connection.'.sancion,id_sancion,'.$this->id_sancion.',id_sancion',
                'fecha_sancion' =>'nullable|date',
                'razon' =>'nullable|max:255',
                'puntos_sancion' =>'nullable',
                'suspendido' =>'nullable|boolean',
                'juegos_suspendidos' =>'nullable',
                'expulsado' =>'nullable|boolean',
                'id_delegacion' =>'nullable|exists:'.$this->connection.'.delegacion,id_delegacion',
                'id_competencia' =>'nullable|exists:'.$this->connection.'.competencia,id_competencia'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

