<?php
/**Generate by ASGENS
*@author Yoan  
*@date Fri May 09 13:47:32 GMT-04:00 2025  
*@time Fri May 09 13:47:32 GMT-04:00 2025  
*/
namespace Modules\security\Models;


use App\Models\BaseModel;

use Illuminate\Support\Carbon;

/**
 * Este es la clase modelo para la tabla log.
 *
 * Los siguientes son los campos de la tabla 'log':
 * @property integer $id
 * @property string $nombre_accion
 * @property string $tabla
 * @property string $record
 * @property string $ip
 * @property Carbon $creado
 * @property Carbon $actualizado
 * @property integer $id_usuario

 * Los siguientes son las relaciones de este modelo :

 * @property Usuarios $usuario
 **/



class Log extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'log';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


/**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['usuario'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Log';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id',
      'nombre_accion',
      'tabla',
      'record',
      'ip',
      'creado',
      'actualizado',
      'id_usuario'
    ];

	 /**
     * Get the Usuarios
     */
	  public function usuario()
		{
			return $this->belongsTo(Usuarios::class,'id_usuario','id_usuario');
		}



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'id' =>'required|unique:'.$this->connection.'.log',
                'nombre_accion' =>'nullable|max:255',
                'tabla' =>'nullable|max:255',
                'record' =>'nullable|max:255',
                'ip' =>'nullable|max:255',
                'creado' =>'nullable|date',
                'actualizado' =>'nullable|date',
                'id_usuario' =>'nullable|exists:'.$this->connection.'.usuarios,id_usuario'
            ],
            'update'=>[
                'id' =>'required|unique:'.$this->connection.'.log,id,'.$this->id.',id',
                'nombre_accion' =>'nullable|max:255',
                'tabla' =>'nullable|max:255',
                'record' =>'nullable|max:255',
                'ip' =>'nullable|max:255',
                'creado' =>'nullable|date',
                'actualizado' =>'nullable|date',
                'id_usuario' =>'nullable|exists:'.$this->connection.'.usuarios,id_usuario'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

