<?php
/**Generate by ASGENS
*@author Yoan  
*@date Fri May 09 13:47:32 GMT-04:00 2025  
*@time Fri May 09 13:47:32 GMT-04:00 2025  
*/
namespace Modules\security\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla permisos.
 *
 * Los siguientes son los campos de la tabla 'permisos':
 * @property integer $id_permiso
 * @property string $nombre_permiso
 * @property string $code
 * @property string $modulo
 * @property string $controller
 * @property string $accion
 * @property boolean $habilitado

 * Los siguientes son las relaciones de este modelo :

 * @property Rol_permiso[] $array_rol_permiso
 **/



class Permisos extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'permisos';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_permiso';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_rol_permiso'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Permisos';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_permiso',
      'nombre_permiso',
      'code',
      'modulo',
      'controller',
      'accion',
      'habilitado'
    ];


	 /**
     * 
     * Get array_rol_permiso
     */
	  public function array_rol_permiso()
		{
			return $this->hasMany(Rol_permiso::class,'id_permiso','id_permiso');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'nombre_permiso' =>'nullable|max:255',
                'code' =>'nullable|max:255',
                'modulo' =>'nullable|max:255',
                'controller' =>'nullable|max:255',
                'accion' =>'nullable|max:255',
                'habilitado' =>'nullable|boolean'
            ],
            'update'=>[
                'id_permiso' =>'required|unique:'.$this->connection.'.permisos,id_permiso,'.$this->id_permiso.',id_permiso',
                'nombre_permiso' =>'nullable|max:255',
                'code' =>'nullable|max:255',
                'modulo' =>'nullable|max:255',
                'controller' =>'nullable|max:255',
                'accion' =>'nullable|max:255',
                'habilitado' =>'nullable|boolean'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

