<?php
/**Generate by ASGENS
*@author Yoan  
*@date Fri May 09 13:47:32 GMT-04:00 2025  
*@time Fri May 09 13:47:32 GMT-04:00 2025  
*/
namespace Modules\security\Models;


use App\Models\BaseModel;

use Illuminate\Support\Carbon;

/**
 * Este es la clase modelo para la tabla rol.
 *
 * Los siguientes son los campos de la tabla 'rol':
 * @property integer $id_rol
 * @property string $nombre_rol
 * @property boolean $activo
 * @property Carbon $creado
 * @property Carbon $actualizado

 * Los siguientes son las relaciones de este modelo :

 * @property Rol_permiso[] $array_rol_permiso
 * @property Usuario_rol[] $array_usuario_rol
 **/



class Rol extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'rol';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_rol';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_rol_permiso','array_usuario_rol'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Rol';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_rol',
      'nombre_rol',
      'activo',
      'creado',
      'actualizado'
    ];


	 /**
     * 
     * Get array_rol_permiso
     */
	  public function array_rol_permiso()
		{
			return $this->hasMany(Rol_permiso::class,'id_rol','id_rol');
		}

	 /**
     * 
     * Get array_usuario_rol
     */
	  public function array_usuario_rol()
		{
			return $this->hasMany(Usuario_rol::class,'id_rol','id_rol');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'nombre_rol' =>'nullable|max:255',
                'activo' =>'nullable|boolean',
                'creado' =>'nullable|date',
                'actualizado' =>'nullable|date'
            ],
            'update'=>[
                'id_rol' =>'required|unique:'.$this->connection.'.rol,id_rol,'.$this->id_rol.',id_rol',
                'nombre_rol' =>'nullable|max:255',
                'activo' =>'nullable|boolean',
                'creado' =>'nullable|date',
                'actualizado' =>'nullable|date'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

