<?php
/**Generate by ASGENS
*@author Yoan  
*@date Fri May 09 13:47:32 GMT-04:00 2025  
*@time Fri May 09 13:47:32 GMT-04:00 2025  
*/
namespace Modules\security\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla rol_permiso.
 *
 * Los siguientes son los campos de la tabla 'rol_permiso':
 * @property integer $id_rol_permiso
 * @property integer $id_rol
 * @property integer $id_permiso

 * Los siguientes son las relaciones de este modelo :

 * @property Permisos $permiso
 * @property Rol $rol
 **/



class Rol_permiso extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'rol_permiso';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_rol_permiso';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['permiso','rol'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Rol_permiso';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_rol_permiso',
      'id_rol',
      'id_permiso'
    ];

	 /**
     * Get the Permisos
     */
	  public function permiso()
		{
			return $this->belongsTo(Permisos::class,'id_permiso','id_permiso');
		}

	 /**
     * Get the Rol
     */
	  public function rol()
		{
			return $this->belongsTo(Rol::class,'id_rol','id_rol');
		}



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'id_rol' =>'nullable|exists:'.$this->connection.'.rol,id_rol',
                'id_permiso' =>'nullable|exists:'.$this->connection.'.permisos,id_permiso'
            ],
            'update'=>[
                'id_rol_permiso' =>'required|unique:'.$this->connection.'.rol_permiso,id_rol_permiso,'.$this->id_rol_permiso.',id_rol_permiso',
                'id_rol' =>'nullable|exists:'.$this->connection.'.rol,id_rol',
                'id_permiso' =>'nullable|exists:'.$this->connection.'.permisos,id_permiso'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

