<?php
/**
*@author Yoan  
*@date Fri May 09 13:47:32 GMT-04:00 2025  
*@time Fri May 09 13:47:32 GMT-04:00 2025  
*/
namespace Modules\security\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla usuario_rol.
 *
 * Los siguientes son los campos de la tabla 'usuario_rol':
 * @property integer $id_user_rol
 * @property integer $id_usuario
 * @property integer $id_rol

 * Los siguientes son las relaciones de este modelo :

 * @property Usuarios $usuario
 * @property Rol $rol
 **/



class Usuario_rol extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'usuario_rol';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'db';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id_user_rol';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['usuario','rol'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Usuario_rol';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id_user_rol',
      'id_usuario',
      'id_rol'
    ];

	 /**
     * Get the Usuarios
     */
	  public function usuario()
		{
			return $this->belongsTo(Usuarios::class,'id_usuario','id_usuario');
		}

	 /**
     * Get the Rol
     */
	  public function rol()
		{
			return $this->belongsTo(Rol::class,'id_rol','id_rol');
		}



    protected function rules($scenario='create')
    {
      $uniqueCombo = 'unique:'.$this->connection.'.usuario_rol,id_rol,NULL,id_user_rol,id_usuario,' . $this->id_usuario;
      $rules=[
        'create'=>[
          'id_usuario' =>'required|exists:'.$this->connection.'.usuarios,id_usuario',
          'id_rol' =>'required|exists:'.$this->connection.'.rol,id_rol|' . $uniqueCombo
        ],
        'update'=>[
          'id_user_rol' =>'required|unique:'.$this->connection.'.usuario_rol,id_user_rol,'.$this->id_user_rol.',id_user_rol',
          'id_usuario' =>'required|exists:'.$this->connection.'.usuarios,id_usuario',
          'id_rol' =>'required|exists:'.$this->connection.'.rol,id_rol|' . $uniqueCombo
        ]
      ];
      if(!isset($rules[$scenario]))
        throw new \Exception('Scenario '.$scenario.' not exist');
      return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

